apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    k8s.score.dev/workload-name: helloworld
  labels:
    app.kubernetes.io/instance: helloworld-81bbefb9ab
    app.kubernetes.io/name: helloworld
    env: prod
  name: helloworld
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: helloworld-81bbefb9ab
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        k8s.score.dev/workload-name: helloworld
      labels:
        app.kubernetes.io/instance: helloworld-81bbefb9ab
        app.kubernetes.io/managed-by: score-k8s
        app.kubernetes.io/name: helloworld
    spec:
      containers:
      - image: ghcr.io/pr3s3nt/helloworld:a6a3e22578b48a10de010b0a55e77ad54a40f3cf
        name: web
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
      imagePullSecrets:
      - name: registry-pull
status: {}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  annotations:
    k8s.score.dev/resource-guid: 63c1f8e2-7904-47f7-8b83-fef9bc4d1f3f
    k8s.score.dev/resource-uid: route.default#helloworld.route
    k8s.score.dev/source-workload: helloworld
  labels:
    app.kubernetes.io/name: route-helloworld-63c1f8e2
  name: route-helloworld-63c1f8e2
spec:
  hostnames:
  - helloworld.127.0.0.1.nip.io
  parentRefs:
  - name: ingress-gateway
    namespace: traefik
  rules:
  - backendRefs:
    - name: helloworld
      port: 80
    matches:
    - path:
        type: PathPrefix
        value: /
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    k8s.score.dev/workload-name: helloworld
  labels:
    app.kubernetes.io/instance: helloworld-81bbefb9ab
    app.kubernetes.io/name: helloworld
  name: helloworld
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app.kubernetes.io/instance: helloworld-81bbefb9ab
status:
  loadBalancer: {}
